"""Agrega reglas de transicion

Revision ID: 2f8e30eff091
Revises: d4e95659c18e
Create Date: 2026-09-12 00:44:56.193398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8e30eff091'
down_revision = 'd4e95659c18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_transicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('area_origen_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=80), nullable=False),
    sa.Column('area_destino_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_destino_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_origen_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id', 'area_origen_id', 'evento', 'area_destino_id', 'servicio_id', name='uq_regla_transicion')
    )
    with op.batch_alter_table('reglas_transicion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reglas_transicion_area_destino_id'), ['area_destino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_transicion_area_origen_id'), ['area_origen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_transicion_evento'), ['evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_transicion_sede_id'), ['sede_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_transicion_servicio_id'), ['servicio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas_transicion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reglas_transicion_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_reglas_transicion_sede_id'))
        batch_op.drop_index(batch_op.f('ix_reglas_transicion_evento'))
        batch_op.drop_index(batch_op.f('ix_reglas_transicion_area_origen_id'))
        batch_op.drop_index(batch_op.f('ix_reglas_transicion_area_destino_id'))

    op.drop_table('reglas_transicion')
    # ### end Alembic commands ###
