"""agrega servicios por sede

Revision ID: 3737f982042c
Revises: ca39cb952448
Create Date: 2026-09-09 00:34:35.560637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3737f982042c'
down_revision = 'ca39cb952448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio_sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id', 'servicio_id', name='uq_servicio_sede')
    )
    with op.batch_alter_table('servicio_sedes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicio_sedes_sede_id'), ['sede_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicio_sedes_servicio_id'), ['servicio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio_sedes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicio_sedes_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_servicio_sedes_sede_id'))

    op.drop_table('servicio_sedes')
    # ### end Alembic commands ###
