"""Agrega vinculo de sedes con fundacion

Revision ID: 59e543943ce1
Revises: 06428d478338
Create Date: 2026-09-03 00:33:39.358270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e543943ce1'
down_revision = '06428d478338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ubicacion_fundacion', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sedes_id_ubicacion_fundacion'), ['id_ubicacion_fundacion'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sedes_id_ubicacion_fundacion'))
        batch_op.drop_column('id_ubicacion_fundacion')

    # ### end Alembic commands ###
