"""Agrega solicitudes de area

Revision ID: 5b99816ccab7
Revises: b8a79d539017
Create Date: 2026-09-23 16:04:17.904892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b99816ccab7'
down_revision = 'b8a79d539017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atencion_id', sa.Integer(), nullable=False),
    sa.Column('area_origen_id', sa.Integer(), nullable=True),
    sa.Column('area_destino_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('prioridad', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['area_destino_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_origen_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_area_area_destino_id'), ['area_destino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_area_area_origen_id'), ['area_origen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_area_atencion_id'), ['atencion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_area_atencion_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_area_area_origen_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_area_area_destino_id'))

    op.drop_table('solicitudes_area')
    # ### end Alembic commands ###
