"""Agrega modalidad a servicios de atencion

Revision ID: 67cccf7bac45
Revises: 3737f982042c
Create Date: 2026-09-09 23:00:51.361381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cccf7bac45'
down_revision = '3737f982042c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atencion_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidad', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atencion_servicios', schema=None) as batch_op:
        batch_op.drop_column('modalidad')

    # ### end Alembic commands ###
