"""Agrega pausas de turnos

Revision ID: b8a79d539017
Revises: d7582a472c37
Create Date: 2026-09-23 15:39:15.155389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a79d539017'
down_revision = 'd7582a472c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pausas_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_area_id', sa.Integer(), nullable=False),
    sa.Column('motivo_codigo', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('tiempo_objetivo_segundos', sa.Integer(), nullable=True),
    sa.Column('usuario_inicio', sa.String(length=100), nullable=True),
    sa.Column('usuario_fin', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['turno_area_id'], ['turnos_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pausas_turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pausas_turno_turno_area_id'), ['turno_area_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pausas_turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pausas_turno_turno_area_id'))

    op.drop_table('pausas_turno')
    # ### end Alembic commands ###
