"""agrega areas por sede

Revision ID: ca39cb952448
Revises: 59e543943ce1
Create Date: 2026-09-06 00:56:29.380488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca39cb952448'
down_revision = '59e543943ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sede_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden_visual', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id', 'area_id', name='uq_sede_area')
    )
    with op.batch_alter_table('sede_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sede_areas_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sede_areas_sede_id'), ['sede_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sede_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sede_areas_sede_id'))
        batch_op.drop_index(batch_op.f('ix_sede_areas_area_id'))

    op.drop_table('sede_areas')
    # ### end Alembic commands ###
