"""Agrega reglas de destino inicial

Revision ID: d4e95659c18e
Revises: 67cccf7bac45
Create Date: 2026-09-12 00:32:16.188242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e95659c18e'
down_revision = '67cccf7bac45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_destino_inicial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('condicion', sa.String(length=50), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id', 'condicion', 'area_id', 'servicio_id', name='uq_regla_destino_inicial')
    )
    with op.batch_alter_table('reglas_destino_inicial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reglas_destino_inicial_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_destino_inicial_condicion'), ['condicion'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_destino_inicial_sede_id'), ['sede_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_destino_inicial_servicio_id'), ['servicio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas_destino_inicial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reglas_destino_inicial_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_reglas_destino_inicial_sede_id'))
        batch_op.drop_index(batch_op.f('ix_reglas_destino_inicial_condicion'))
        batch_op.drop_index(batch_op.f('ix_reglas_destino_inicial_area_id'))

    op.drop_table('reglas_destino_inicial')
    # ### end Alembic commands ###
