"""Agrega area previa a servicios por sede

Revision ID: d7582a472c37
Revises: 2f8e30eff091
Create Date: 2026-09-23 00:04:07.973532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7582a472c37'
down_revision = '2f8e30eff091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio_sedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_previa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_servicio_sedes_area_previa_id'), ['area_previa_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_servicio_sedes_area_previa_id_areas',
            'areas',
            ['area_previa_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio_sedes', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_servicio_sedes_area_previa_id_areas',
            type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_servicio_sedes_area_previa_id'))
        batch_op.drop_column('area_previa_id')

    # ### end Alembic commands ###
