"""estructura inicial turnero

Revision ID: e76520dcc61a
Revises: 
Create Date: 2026-08-30 23:49:47.824003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76520dcc61a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('genera_cola', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden_visual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('doctores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('consultorio', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('numero_afiliacion', sa.String(length=50), nullable=True),
    sa.Column('afiliado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_afiliacion')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requiere_pago', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('nombre_paciente', sa.String(length=200), nullable=False),
    sa.Column('fecha_cita', sa.Date(), nullable=False),
    sa.Column('hora_programada', sa.Time(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctores.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atenciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('nombre_paciente', sa.String(length=200), nullable=False),
    sa.Column('tipo_llegada', sa.String(length=20), nullable=False),
    sa.Column('afiliado_al_llegar', sa.Boolean(), nullable=False),
    sa.Column('servicio_inicial_id', sa.Integer(), nullable=True),
    sa.Column('doctor_solicitado_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_hora_llegada', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['doctor_solicitado_id'], ['doctores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_inicial_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atenciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atenciones_folio'), ['folio'], unique=True)

    op.create_table('atencion_servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atencion_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('requiere_pago', sa.Boolean(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atencion_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnos_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atencion_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('numero_turno', sa.String(length=30), nullable=False),
    sa.Column('tipo_prioridad', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_entrada_cola', sa.DateTime(), nullable=False),
    sa.Column('fecha_llamado', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('veces_omitido', sa.Integer(), nullable=False),
    sa.Column('ultima_omision', sa.DateTime(), nullable=True),
    sa.Column('posicion_manual', sa.Integer(), nullable=True),
    sa.Column('prioridad_manual', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctores.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turnos_area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_area_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turnos_area_atencion_id'), ['atencion_id'], unique=False)

    op.create_table('historial_turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_area_id', sa.Integer(), nullable=True),
    sa.Column('atencion_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_id'], ['atenciones.id'], ),
    sa.ForeignKeyConstraint(['turno_area_id'], ['turnos_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_turnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_turnos_atencion_id'), ['atencion_id'], unique=False)

    op.create_table('pago_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_detalle')
    with op.batch_alter_table('historial_turnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_turnos_atencion_id'))

    op.drop_table('historial_turnos')
    with op.batch_alter_table('turnos_area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnos_area_atencion_id'))
        batch_op.drop_index(batch_op.f('ix_turnos_area_area_id'))

    op.drop_table('turnos_area')
    op.drop_table('pagos')
    op.drop_table('atencion_servicios')
    with op.batch_alter_table('atenciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atenciones_folio'))

    op.drop_table('atenciones')
    op.drop_table('citas')
    op.drop_table('servicios')
    op.drop_table('pacientes')
    op.drop_table('jornadas')
    op.drop_table('doctores')
    op.drop_table('areas')
    # ### end Alembic commands ###
